# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Install dependencies for Google Chrome
RUN apt-get update && apt-get install -y wget gnupg ca-certificates fonts-liberation libasound2 libnspr4 libnss3 libxss1 lsb-release

# Add Google Chrome repository and install Chrome
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list \
    && apt-get update \
    && apt-get install -y google-chrome-stable \
    && apt-get clean

WORKDIR /app

# Copy source code
COPY . .

# Upgrade pip and install build backend
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir hatchling

# Build and install the package
RUN pip install --no-cache-dir .

# Expose any ports if necessary (none required for stdio based MCP)

CMD ["mcp-chrome-server"]
